# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'DeliveryTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DeliveryTest
	pod 'RxSwift', '~> 4.0'
	pod 'RxCocoa', '~> 4.0'
	pod 'Alamofire'
	pod 'ObjectMapper'
	pod 'AlamofireObjectMapper'
	pod 'Kingfisher', '~> 4.0'
  pod 'RealmSwift'
  pod 'RxRealm'
	pod 'SnapKit', '~> 5.0.0'
end
