# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'DeliveryTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DeliveryTest
	pod 'RxSwift', '~> 4.0'
	pod 'RxCocoa', '~> 4.0'
	pod 'Alamofire', '~> 4.5'
	pod 'ObjectMapper', '~> 3.3'
	pod 'AlamofireObjectMapper', '~> 5.0'
	pod 'Kingfisher', '~> 4.0'
	pod 'SwiftyJSON', '~> 4.0'
end
